name: Build and Push Docker Image

on:
    push:
        branches:
            - main
        tags:
            - 'v*..'

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write # For uploading Github Container Registry (GHCR)
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Determine image tag
              id: vars
              run: |
                REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
                echo "REPO_NAME=${REPO_LOWER}" >> $GITHUB_ENV

                if [[ "${GITHUB_REF}" == "tag" ]]; then
                    echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
                else
                    echo "TAG=latest" >> $GITHUB_ENV
                fi

            - name: Build Docker Image
              run: |
                docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG }} ./backend
            
            - name: Push Docker Image
              run: |
                docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}




      
