

name: CI/CD Frontend - Build and Push Docker Image


on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' 
    paths:
      - 'frontend/**' 
#cambiosssss
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          
          images: ghcr.io/${{ github.repository }}/frontend_app 
          tags: |
            type=ref,event=tag         
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}